### ISSUE TITLE
use cases page is not linked: https://ethereum.github.io/use-cases

### ISSUE THREAD

**Issue by sueszli** [ethereum/solidity-website#1]

**Comment by wackerow** [comment]
https://ethereum.github.io/use-cases Is not a valid path... did you see this link somewhere @sueszli? Should be https://soliditylang.org/use-cases or technically also https://ethereum.github.io/solidity-website/use-cases

Going to close this out, but feel free to reopen if you have an issue.

**Comment by sueszli** [comment]
I initially just checked all links from the github pages home page.

I just rechecked and it all worked fine! Thank you!
