### ISSUE TITLE
Bug report: docs sidebar scrolling does not work when choosing a branch

### ISSUE THREAD

**Issue by 0x0OZ** [ethereum/solidity-website#31]
### Describe the bug

Can't scroll through compiler versions in the docs(sidebar), the scroll works through sections, but it stops working when trying to choose a different branch.

### To reproduce

1. Go to the [docs](https://docs.soliditylang.org/)
2. Click on the version to change the branch bottom left
3. Try to scroll in the sidebar

### Expected behavior

Sidebar scrolling should work.

### Screenshots

scroll works:
![image](https://github.com/ethereum/solidity-website/assets/52073989/6c7bf2dc-5277-45e8-8902-b6ef4b3fe5d5)
the scroll bar is gone for the sidebar:
![image](https://github.com/ethereum/solidity-website/assets/52073989/14eb8f37-82d6-4b19-b16f-7d53866b3790)

### Desktop (please complete the following information)

- OS: Manjaro Linux
- Tested Browsers: Google Chrome and Firefox

**Comment by wackerow** [comment]
Hey @0x0OZ, thanks for filing this! 🙏 

The docs portion of this site is actually maintained separately via the [ethereum/solidity](https://github.com/ethereum/solidity) repo. This issue has been filed (https://github.com/ethereum/solidity/issues/14429) and a patch is up (https://github.com/ethereum/solidity/pull/14431), awaiting review from the Solidity repo maintainers. 

This was helpful though as it surfaces how easy it is to mix up where to post issues about the docs. I'll add some more info to the README and issue templates for this repo to make it more clear to contributors the distinction between the core "solidity website" (this repo) and the "docs" (Solidity repo) to help get folks to the right place in the future. Going to close this out in lieu of the noted issue/PR on that repo. Thanks again!
