### ISSUE TITLE
`stable` link disappeared from the version popup in the docs

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity-website#42]
https://docs.soliditylang.org/en/stable/ points at the latest stable version of the docs (i.e. `v0.8.21` right now) but it's not present in the popup version menu.

On the other hand `develop` (which is equivalent to `latest` and therefore redundant) does show up.

This does not seem to be caused by the recent restyling. Looking at older versions, the `stable` link disappeared in 0.8.15.

![docs-version-popup](https://github.com/ethereum/solidity/assets/137030/bbe692e3-cafe-49f8-ba7e-54402f03f0bb)

**Comment by NunoFilipeSantos** [comment]
@wackerow can you help here?

**Comment by wackerow** [comment]
This may be in the RTD settings... afk at the moment but can check into this

**Comment by wackerow** [comment]
<img width="853" alt="image" src="https://github.com/ethereum/solidity-website/assets/54227730/8e0fce43-23ac-458e-87ab-543e3019afb0">

Looking at https://readthedocs.org/projects/solidity/versions/ the `stable` branch does appear to be noted and pointing to the v0.8.21 build, but not sure why this isn't showing in the flyover menu.

Cursory search didn't provide too much on this... can take another look when time offers. If it's something desired, could always add some logic to just add this in manually.

**Comment by NunoFilipeSantos** [comment]
@ekpyron and @cameel you were the 2 ones experiencing this, can you give some feedback?

**Comment by cameel** [comment]
I'd expect it to be a simple bug in the code or in RTD settings. If not, maybe it's not worth the effort. At least I would not go as a far as artificially hacking it into that menu with JS.

**Comment by ekpyron** [comment]
I just had a quick look at the RTD settings - ``stable`` was marked as "active", but also as "hidden" - I may have changed that when we had issues with the docs builds in one of the previous releases and failed to change it back...
We may be able to trigger rebuilds for the docs, which may bring it back - haven't looked into that yet.

**Comment by franzihei** [comment]
`stable` is showing in [`latest`](https://docs.soliditylang.org/en/latest/) so I guess we can close this issue for now?

**Comment by cameel** [comment]
Yeah. The link is back even in old versions. Weird.
