### ISSUE TITLE
Unable to scroll version list

### ISSUE THREAD

**Issue by imsoumya18** [ethereum/solidity-website#43]
### Describe the bug

After clicking the version list from the stable site, no option to collapse the list. Also, there is no option to scroll the lists causing the upper part to remain hidden.

![image](https://github.com/ethereum/solidity-website/assets/50456734/e0d4dfe4-398e-4100-87a1-4e416b849ef1)

### To reproduce

1. Go to 'https://docs.soliditylang.org/en/stable/'
2. Click on 'stable' at the bottom left corner
3. See the error

### Expected behavior

There should be a scroll bar & an option to collapse the list too

**Comment by wackerow** [comment]
Yeah, this has been patched but as was noted, the docs are frozen for each release and do not change, so unfortunately that bug will persist for that version. Thanks for the report though @imsoumya18 🙏, going to close this out.
