### ISSUE TITLE
Anchor links in the navbar are broken

### ISSUE THREAD

**Issue by qd-qd** [ethereum/solidity-website#44]
### Describe the bug

Since the rebranding, there is a regression in the anchor links in the navbar. They now require two clicks to be redirected to the desired section.

### To reproduce

1. Go to Types
2. Click on `Fixed-size byte arrays`
3. Nothing happens
4. Click again on `Fixed-size byte arrays`
5. Now the page scroll to the desired section

### Expected behavior

Two clicks on the anchor links are expected today for the page to scroll to the desired section. The same behavior should be triggered in only one click.

### Desktop (please complete the following information)

- Device: MacOS 16" Intel chip
- OS: Ventura 13.4.1
- Browser: Chrome
- Version: 115.0.5790.114

**Comment by franzihei** [comment]
This was fixed in https://github.com/ethereum/solidity/pull/14439.

Should work now if you go to https://docs.soliditylang.org/en/latest and in all upcoming releases (doc versions and doc changes are linked to releases).
