### ISSUE TITLE
Enable solidity doc readers to switch back to old doc style

### ISSUE THREAD

**Issue by adu-web3** [ethereum/solidity-website#47]
### Is your feature request related to a problem? Please describe.

For the current doc page style, the background is grey while the text is like purple, which means that the
text would not stand out as much as black against white. So could you enable users to switch back to old version doc style?

### Describe the solution you'd like

Provide the old doc page style as an alternative so that users could choose favorable style

### Describe alternatives you've considered

Or just switch back to old style

**Comment by franzihei** [comment]
Did you try switching to dark mode? The contrast between text and background is higher there: 
<img width="929" alt="image" src="https://github.com/ethereum/solidity-website/assets/41991517/b9236d49-99f5-42e4-970d-fbbf1b72bc92">

**Comment by wackerow** [comment]
Hey @adu-web3, thanks for the note... Curious if you found the dark-mode colors more tolerable in terms of color contrast.

I don't see reverting back to the original color scheme as an option at this point, but this does raise the idea that a high-contrast mode could be something developed in the future. This would require some bandwidth that I don't personally have at the moment, but can discuss going forward.

**Comment by wackerow** [comment]
Closing this out, but feel free to reopen conversation as-needed.
