### ISSUE TITLE
Enable IPFS hosting

### ISSUE THREAD

**Issue by r0qs** [ethereum/solidity-website#49]
### Is your feature request related to a problem? Please describe.

Hi, we want to deploy the new version of the Solidity website on IPFS (see the old version here: https://soliditylang.eth.link/), however as the website now uses Next.js it seems that some configuration is required to use relative URLs when performing the static exporting. 

### Describe the solution you'd like

Enable the deployment of the website on IPFS. I'm not sure if only the conversion of absolute links to relative links would be sufficient. After a quick search on the web, it seems that more things may be needed, see: https://github.com/vercel/next.js/discussions/32216#discussioncomment-1766243. So I honestly don't have a better description of the possible solution.

These comments may be relevant as well: https://github.com/vercel/next.js/discussions/32216#discussioncomment-5649788 and https://github.com/vercel/next.js/discussions/32216#discussioncomment-1766247

### Describe alternatives you've considered

None.

**Comment by franzihei** [comment]
This would be solved with the fleek integration. Creating a devops issue for it!
@wackerow did a PR for the fleek config which I merged already.

as he described in Discord:
> To make sure it's clear, our GitHub Pages deployment was/is already setup to export a static site (exported to docs to conform to Pages standard) which just needs to be uploaded to IPFS... 
> Fleek will do all of that automatically with each update to `main` if you link the repo and use the settings I mentioned (in PR above)... you'll just link the IPNS content hash they give you to the ENS and you should then be able to mostly forget about it.

So will try to do that once we have the fleek integration in our repo (currently seems to be a permissions issue).

**Comment by franzihei** [comment]
Done!
