### ISSUE TITLE
[Bug] Inconsistent Display of Up-and-Right Arrow on Certain Android Devices

### ISSUE THREAD

**Issue by minimalsm** [ethereum/solidity-website#6]
Requires more investigation:

On certain Android devices, the text arrow (`This is a link ↗`) is displayed as an emoji arrow (This is a link ↗️) instead. The expected behaviour is for the arrow to always appear as text (`This is a link ↗`). The cause, the exact Android versions, and the devices affected need to be identified. 

Community input and suggestions for potential solutions are welcome ❤️ 

<img width="225" alt="Screenshot 2023-07-13 at 11 25 51" src="https://github.com/ethereum/solidity-website/assets/62268199/e4d42de2-1ab2-4dd9-a80c-ebdf33947ce7">

**Comment by wackerow** [comment]
There is an alternate north east arrow that we could use, ➚ ([unicode 279A](https://graphemica.com/%E2%9E%9A))... I just tried it on Android using BrowserStack and it renders as a regular arrow without a box, just slightly different than the previous NE arrow:

<img width="526" alt="Screenshot 2023-07-20 at 22 04 11" src="https://github.com/ethereum/solidity-website/assets/54227730/2d44d250-e3bc-45a3-a999-6fa2e6a28e99">

@minimalsm https://solidity-website-git-ne-arrow-wackerow.vercel.app/ Any way you could try this link with the same device that produced your screenshot above?

If we want to go with this, I can put up a PR, and also update the Docs with the same arrow to make sure the nav bars still match.

**Comment by wackerow** [comment]
https://www.shellhacks.com/disable-emoji-stop-rendering-html-code-as-emoji/

^ This website explains solution, although it has them flipped in the explainer... it should be:

> `&#xFE0E;` – disable emoji and render the previous glyph as a text
> `&#xFE0F;` – display the previous glyph as an emoji

Can try it here in GitHub:

`↗&#xFE0F;` => ↗&#xFE0F;
`↗&#xFE0E;` => ↗&#xFE0E;

(Thanks to @christy-pdx for the tip!)
